### ISSUE TITLE
Build instructions?

### ISSUE THREAD

**Issue by bobdanek** [Megalan/PatreonDownloader#1]
I'd like to use this but I'm entirely unfamiliar with building .NET code. I've tried loading it up in Visual Studio with the .net core 2.2 runtime installed and it builds/publishes dll files, but never a .exe.

I've tried building the .sln file and each individual project within and just can't figure out how to get an .exe out of this code.

I've also tried `dotnet build` and `dotnet publish` in the repo root and in each project and get the same results (only dlls, no executable)

Thank you!

**Comment by Megalan** [comment]
I definitely plan to write build instructions when I have some free time.

I have not yet configured a self-contained exe profile so you have 2 options if you want to run this application:
1. execute `dotnet run` command in `PatreonDownloader.App` folder
2. execute `dotnet build` command in `PatreonDownloader.App` and then go to `PatreonDownloader.App\bin\Debug\netcoreapp2.2` and execute `dotnet PatreonDownloader.App.dll` command

**Comment by bobdanek** [comment]
That works great, thanks so much! Fantastic work on this

**Comment by Megalan** [comment]
Thanks! Glad you find it useful. I'll leave this issue open until I make a proper wiki page with build instructions.

**Comment by Megalan** [comment]
Added [**build instructions wiki page**](https://github.com/Megalan/PatreonDownloader/wiki/Build-instructions) as well as publishing profiles used to build self-contained executables.
