### ISSUE TITLE
Dotnet Core instructions (Linux, Mac etc.)

### ISSUE THREAD

**Issue by bobobo1618** [Megalan/PatreonDownloader#7]
I was able to get this running on Linux with Dotnet Core really easily. Steps were:

- Install dotnet core
- Clone the repository
- Run `dotnet restore`
- Run `dotnet msbuild -property:Configuration=Release`
- Run `PatreonDownloader.App/bin/Release/netcoreapp3.1/PatreonDownloader.App`

Just FYI in case you're interested or want to add instructions.

**Comment by Megalan** [comment]
Thanks for the information! I'll do some testing on my side and update the documentation accordingly.

**Comment by Megalan** [comment]
Documentation has been updated and release with pre-built Linux binaries has been uploaded. Both PatreonDownloader and Google Drive plugin are now considered as compatible with Linux. 

macOS is still considered experimental and no pre-built binaries are provided for it as there are no confirmation that the software runs correctly under it.
