### ISSUE TITLE
Ignore duplicates

### ISSUE THREAD

**Issue by kdliu86** [Megalan/PatreonDownloader#8]
Is it possible to implement the ability to ignore duplicates?  This would provide the ability to pause/resume, or to continue in case something disconnects or goes out.

**Comment by Megalan** [comment]
This check already exists. If downloaded folder contains file with the same name it will not be downloaded again.

If you mean something else please clarify. If you are satisfied with this answer please let me know so I can close the issue.

**Comment by kdliu86** [comment]
Ahh that's all, thank you.
